### PR TITLE
Rebased 'disk_handling'

### PR DESCRIPTION
**Pull request by esc**
Cleaned up the history from #140 and #152.

Commits now apply (almost) cleanly to current master.

### CODE REVIEW

**Comment by esc** [comment]
@FrancescElies @CarstVaartjes there seems to be one last test-failure. Looks like something with the append?

**Comment by esc** [comment]
Another thing that surprises me, is that ``mock`` wasn't added as a dependency, but Travis-CI isn't complaining.

**Comment by esc** [comment]
BTW: if you want to add commits to this, feel free to `reset --hard`` and ``push --force`` #152.

**Comment by esc** [comment]
I added an entry for the changelog too, please check it.

**Comment by esc** [comment]
Lastly, I might be mistaken, but the ``move`` kwarg doesn't seem to be tested.

**Comment by FrancescElies** [comment]
Mock is a preinstalled pip package http://docs.travis-ci.com/user/ci-environment/ but we could add it to dependencies to make it explicit, what do you think?

**Comment by FrancescElies** [comment]
Looking atm at what's failing

**Comment by FrancescElies** [comment]
I see, if fails due to the following commit, this would be the autoflush for a carray on-disk, if this feature is wanted only for ctables, then commit https://github.com/esc/bcolz/commit/11503d06d3769d81f085012b8685bd5ff05ab38a should be discarded. I'll get this commit out of the history if you are ok

**Comment by FrancescElies** [comment]
Without that commit all tests pass see https://travis-ci.org/FrancescElies/bcolz/builds/53055523 
I have no rights to do that on @CarstVaartjes repository, shal I make a new PR? I pushed changes here https://github.com/FrancescElies/bcolz/tree/esc_based_disk_handling

**Comment by CarstVaartjes** [comment]
I think it's correct that the test fails, because append doesn't trigger autoflush yet right?

**Comment by FrancescElies** [comment]
ctable on disk triggers auto_flush after appending, but a stand alone carray on_disk doesn't, this feature was not implemented for carray. If this feature is not needed for a stand alone carray on-disk commit https://github.com/esc/bcolz/commit/11503d06d3769d81f085012b8685bd5ff05ab38a (FlushDiskTest carray) shold be either reverted or deleted

**Comment by CarstVaartjes** [comment]
@esc what do you think? extend autoflush to carrays or leave out the test?

**Comment by esc** [comment]
Not sure. Probably leave it out for the time being, unless you need it.

**Comment by esc** [comment]
I'll remove the commit via interactive rebase and force push

**Comment by esc** [comment]
looks good, I'll let it simmer some more and merge tomorrow.

**Comment by FrancescElies** [comment]
I think for our use case we only need it for ctable, @CarstVaartjes could you please confirm that?

**Comment by CarstVaartjes** [comment]
Yes

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Mar 4, 2015 at 11:58 PM -0800, "Francesc Elies" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think for our use case we only need it for ctable, @CarstVaartjes<https://github.com/CarstVaartjes> could you please confirm that?

-
Reply to this email directly or view it on GitHub<https://github.com/Blosc/bcolz/pull/154#issuecomment-77321638>.


This email (including any attachments to it) is confidential, legally privileged, subject to copyright and is sent for the personal attention of the intended recipient only. If you have received this email in error, please advise us immediately and delete it. You are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Although we have taken reasonable precautions to ensure no viruses are present in this email, we cannot accept responsibility for any loss or damage arising from the viruses in this email or attachments. We exclude any liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided in this email or its attachments, unless that information is subsequently confirmed in writing.

**Comment by esc** [comment]
okay, so the only thing missing is the ``mock`` dependency. I'll add that to a ``test_requirements.txt`` for the time being (with a refactor of setup.py and dependency handling to be done in the future).

**Comment by esc** [comment]
Thanks to y'all who contributed on this one.

**Pull request merged**
