### PR TITLE
Fixing a memory leak

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
depends on #200, merge that first and then rebase this one.

**Comment by esc** [comment]
For details of the leak see:

https://github.com/esc/bcolz/commit/ce7d8c730bdcc249e9b8e90d778c1cf08ea3e556

**Comment by esc** [comment]
Would be nice if this could be confirmed, @FrancescAlted  or @FrancescElies  perhaps you have some spare cycles?

**Comment by FrancescAlted** [comment]
Looks good to me.

**Comment by esc** [comment]
okay, I'll get stuff merged up soon.

**Pull request merged**
