### PR TITLE
Fe/coveralls

### PR DESCRIPTION
**Pull request by FrancescElies**
Tryout coveralls

### CODE REVIEW

**Comment by FrancescAlted** [comment]
This is meant to be merged now, right?

**Comment by FrancescElies** [comment]
:+1: though not sure if the thing with the badge will work, but could be fixed later on

**Comment by FrancescAlted** [comment]
Ok, here we go...

**Comment by FrancescElies** [comment]
cool, badge looks nice too

**Comment by FrancescAlted** [comment]
Oh yeah.  And a 86% coverage is nothing to sneeze at.  Having Cython code covered would be cooler though :)

**Comment by FrancescElies** [comment]
indeed

**Pull request merged**
