### PR TITLE
Carray private methods

### PR DESCRIPTION
**Pull request by FrancescElies**
Related to https://github.com/Blosc/bcolz/issues/22

I started marking some methods with a single underscore, would you prefer double underscore for that?

### CODE REVIEW

**Comment by FrancescAlted** [comment]
No a single underscore is the standard de facto for private methods.  Is that ready for merging?

**Comment by FrancescElies** [comment]
Nope, I just added only two of them

**Comment by FrancescElies** [comment]
Now I could see the following methods:
```
In [1]: c = bz.carray([])

In [2]: c.
c.append          c.dtype           c.nchunks         c.shape
c.atomsize        c.flush           c.ndim            c.size
c.attrs           c.free_cachemem   c.next            c.sum
c.cbytes          c.itemsize        c.open_carray     c.trim
c.chunklen        c.iter            c.partitions      c.view
c.chunks          c.leftover_array  c.purge           c.where
c.copy            c.leftovers       c.reshape         c.wheretrue
c.cparams         c.len             c.resize          
c.create_carray   c.mode            c.rootdir         
c.dflt            c.nbytes          c.safe 
```

Does anybody see something that should not be there?

**Comment by FrancescAlted** [comment]
Well, I propose you put your user's hat and propose some private functions.  If you don't find any candidate, then we have it already.  Actually I don't see that many functions, so I would say this is fine.

**Comment by CarstVaartjes** [comment]
The c.open_carray doesn't make sense as a publicj, as when you create a carray it's opened at that time or a new one is created.

**Comment by FrancescAlted** [comment]
Yeah, and create_carray is in the same bag.

**Comment by FrancescElies** [comment]
Thanks guys, as a user the rest would seem ok to me

**Comment by FrancescAlted** [comment]
Merging.

**Comment by esc** [comment]
You forgot the changelog, entry, I'll ad it now.

**Comment by esc** [comment]
:)

**Comment by esc** [comment]
See: a2473f4082ccd925a83a86e85134fa29ca86ca48

**Comment by FrancescElies** [comment]
cool beans! thanks :)

**Pull request merged**
