### PR TITLE
Refactor how the documentation is built.

### PR DESCRIPTION
**Pull request by esc**
It turns out, that very little of the class and module documentation was
automatically extracted from the Python docstrings. Presumably this is due to
the fact that sphinx + numpy style docstrings have been a bit of a pain to work
with historically. I tried again and it seems that nowadays it actually works
fairly reasonably.

This removes a large amount of technical debt and also potential for
duplication. I didn't take a very close look, but I did see some of the
docstrings already out of sync, so fetching the ones from the source code is
usually a good idea. At least it means we won't need to maintain two copies in
future.

One issue that remains is that Cython functions may not be introspected, so the
signature of each function must be the first line of the docstring. While this
still is duplication it isn't too bad since the actual signature and the
documented signature are very, very close together.

Anyway, I wanted to put this up, to make sure we don't duplicate developer
efforts. (just in case, someone else was wanting to dig into this)

### CODE REVIEW

**Comment by FrancescAlted** [comment]
:+1:

Enviat des del meu iPhone

El 31/03/2015, a les 21:52, Valentin Haenel <notifications@github.com> va escriure:

**Comment by esc** [comment]
In light of #22 maybe I shouldn't waste time on carray now and wait for the refactoring to be resolved first.

**Comment by esc** [comment]
FWIW: I tried to hookup readthedocs but bcolz can't be built there yet, because the build system and dependency handling is not entirely compatible.

In particular Cython isn't being installed, because it isn't listed anywhere in a place where dependencies are installed automatically (setup.py or requirements.txt).

**Comment by esc** [comment]
here goes.

**Pull request merged**
