### PR TITLE
Reroll of #84 and #97 with features of both.

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
This PR is now finished from my perspective and can go into v0.8.0

**Comment by esc** [comment]
Okay, we are all set to merge this in. @FrancescElies I'd like to rebase this branch and then merge it to keep history readable. Will you all be OK with this? Are you basing (in the git sense) any work specifically on this branch?

**Comment by esc** [comment]
So I had a look at all your forks and it *seems* to me that everything will be fine if I rebase. In case you run into any issues, please feel free to get in touch anytime!

**Comment by esc** [comment]
Strap on your seatbelts, public rebase in progress!

**Comment by CarstVaartjes** [comment]
haha, good luck

**Comment by FrancescElies** [comment]
@esc ) It is perfectly fine by me, do what's is best for you. Thank's
(tightening belts!)

**Pull request merged**
