### PR TITLE
Fe/cython coverage

### PR DESCRIPTION
**Pull request by FrancescElies**
https://github.com/Blosc/bcolz/pull/227 continuation

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Hmm, this one cannot be merged because of the recent setup.py big revamp.  Could rebase this PR?

**Comment by FrancescElies** [comment]
I'll rebase but not working yet though

**Comment by FrancescElies** [comment]
So far I couldn't make it work, so I'll try with a smaller project and see if can get cython coverage reported

**Comment by FrancescElies** [comment]
Regarding this approach I tried with a very small cython project, without success.

In the cython mailing list I could read in some places it doesn't work, other people saying it does actually work but coverage.py needs a patch, anyhow I could not draw any clear conclusion.

**Comment by FrancescElies** [comment]
@FrancescAlted , hi I don´t feel I am going to get back to this one any time soon, If I ever discover anything related how to make cython coverage work, I'll come back.
Please feel free to close this one

**Pull request closed without merging**
