### PR TITLE
avoid redundant memory copy in chunk.getudata

### PR DESCRIPTION
**Pull request by esc**
Micorbenchmarks to follow.

### CODE REVIEW

**Comment by esc** [comment]
With the optimization:

```
In [1]: import bcolz

In [2]: a = bcolz.arange(1e6, chunklen=500000)

In [3]: c = a.chunks[0]

In [4]: %timeit u = c.getudata()
1000 loops, best of 3: 704 µs per loop
```

**Comment by esc** [comment]
```
In [1]: import bcolz

In [2]: a = bcolz.arange(1e6, chunklen=500000)

In [3]: c = a.chunks[0]

In [4]: %timeit u = c.getudata()
1000 loops, best of 3: 897 µs per loop
```

**Comment by esc** [comment]
So, all in all not that significant. Though I am not sure you need to check for NULL return when calling ``PyBytes_FromStringAndSize`` in Cython.. Anyone know?

**Comment by esc** [comment]
The timings are actually fairly volatile. I should imagine with larger chunks they may be more reliable.

**Comment by FrancescAlted** [comment]
Well, I would not say that 20% is 'not that significant'.  So I would go ahead and merge this.

**Comment by esc** [comment]
Please go ahead and press the button! :)

**Comment by FrancescAlted** [comment]
I was commanded to "press the button", so here we go!

**Comment by esc** [comment]
Sweeet!

**Comment by FrancescAlted** [comment]
It was as good for you as it was for me?

**Comment by esc** [comment]
Oh... it was amazing!!!

**Comment by FrancescElies** [comment]
I see some sort of ZeroMQ contribution policy being applied here, nice!

**Comment by esc** [comment]
Aw... aw... aw... yeah! https://www.youtube.com/watch?v=bWbJeUEKzc8

**Pull request merged**
