### PR TITLE
fix: asv gets confused with `bcolz` project name

### PR DESCRIPTION
**Pull request by FrancescElies**
@FrancescAlted this should fix https://github.com/Blosc/bcolz/pull/253#issuecomment-145458834
Could you please give it a try

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Woohoo, it works now!  Now I am supposed to find a machine for running the benchmarks and showing the plots right?

**Comment by FrancescAlted** [comment]
Also, any hint on why the original 'bcolz' was causing problems?  Just curious...

**Comment by FrancescElies** [comment]
Honestly, no idea, I saw something with git cloning and at the end of the path appeared three times bcolz, that was a bit strange, I also remembered also changing the name of the project, to bcolz, which to me seemed a sensible name to choose :). 

My guess is that, git tries to create some folder named bcolz at the root level where the conf files is, since here bcolz already exists we get an error.

Better than renaming the underscore would be to move the conf file inside the bench_as folder, ask also creates other directories in the root dir which are a bit annoying, this way everything related to ask would be inside that folder.

**Comment by FrancescElies** [comment]
I did some extra tests, the problem is, as suspected, a folder with the name of the project is being created at the same level of the configuration file if you merge #262 we can have it with the right name

**Comment by FrancescElies** [comment]
Exactly, now you only need a machine and run it

**Comment by FrancescElies** [comment]
but now you need first to change directory `cd bench_as` and then run the asv commands

**Pull request merged**
