### PR TITLE
Fix the 'leftovers' API

### PR DESCRIPTION
**Pull request by esc**
Developing a solution for #71

### CODE REVIEW

**Comment by esc** [comment]
rebased!

**Comment by CarstVaartjes** [comment]
Hi!

just was looking at what's in for 0.9 and saw this which is a really good idea, but I was wondering on how it relates to the chunk iteration? (as this is the last chunk practically, if there are actually leftovers?). But that does mean availability in cython + adjust @FrancescElies his leftover usage?
And on a sidenote, I think that a sliced view for the array is the best because you should only add things to it using the official append method right?

**Comment by FrancescAlted** [comment]
Sorry, I am a bit out of context here, but my view is that if iterators or views would be used, you don't need to expose the leftovers to the user.  IMO, the leftover should be an implementation detail and converted into a private variable (i.e. leading '_').  In case you actually need this, can you describe a use case?

**Comment by esc** [comment]
Yes, it is meant mostly for internal consumption, but it would be nice to refactor this part of the code so that we as developers have an easier time with it. It is something that myself and others stumble upon again and again and it would be nice to have something more intuitive. Using ``_`` and making stuff private is really a good idea and I'll do that.

**Comment by FrancescElies** [comment]
Hi guys, how are you feeling about this one, would you like merge button to be pressed?

**Comment by esc** [comment]
Needs to be integrated with https://github.com/Blosc/bcolz/pull/132/commits and polished (discussed) a bit.

**Comment by esc** [comment]
Also, completely and entirely lacks tests, shame on me.

**Comment by esc** [comment]
Closing in favour of #211

**Pull request closed without merging**
