### PR TITLE
Fix deprecation of DataFrame.from_items

### PR DESCRIPTION
**Pull request by bburan**
Pandas has deprecated DataFrame.from_items. Replace with recommended approach
of DataFrame.from_dict(OrderedDict(...)).

### CODE REVIEW

**Comment by bburan** [comment]
The AppVeyor builds seem to be failing due to an unrelated issue.

**Comment by bburan** [comment]
@FrancescAlted Any chance of getting this merged? `from_items` is officially deprecated now.

**Comment by FrancescAlted** [comment]
Yes, that looks good to me.  Thanks.

**Comment by rs2** [comment]
@FrancescAlted When do you expect to have this changed released please?

**Comment by FrancescAlted** [comment]
Unfortunately bcolz is currently unmaintained.  For more info, see https://github.com/Blosc/bcolz#unmaintained-package-notice.

**Pull request merged**
