### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by FrancescElies**
Some help to #183

### CODE REVIEW

**Comment by FrancescElies** [comment]
Webhooks settings still missing but seems to build and run tests for my fork

**Comment by esc** [comment]
I have no idea, so I trust you on this one. :+1: if it breaks, we'll fix it.

**Comment by esc** [comment]
If you have nothing better to waste your time on, feel free to fix the Appveyor stuff for:

https://github.com/Blosc/python-blosc

too. *evilgrin*

**Comment by esc** [comment]
It works, I'll activate the Blosc group build.

**Comment by esc** [comment]
In fact, I have no idea how to do that. I believe we need a blosc account for appveyor?

**Comment by esc** [comment]
I set it up under my account: https://ci.appveyor.com/project/esc/bcolz

**Comment by esc** [comment]
Appveyor doesn't seem to have the same notion of organizations as github, but this will do for now.

**Pull request merged**
