### PR TITLE
Iterchunks

### PR DESCRIPTION
**Pull request by CarstVaartjes**
Hi,

I've created the iterchunks() function and added a test. Some comments:

- Atm it fails, because _getitem expects a string and not a ndarray(!?!) If anyone could tell me what I'm doing wrong? For details see: https://groups.google.com/forum/#!topic/bcolz/Fk6YpxD5toc 
- It still calculates the leftover elements itself, because nleftover has not been merged into master yet

Some tips to help me fix this, would be very much appreciated!
BR

Carst

### CODE REVIEW

**Comment by FrancescElies** [comment]
Hi Carst,

I see Travis tests passing and Appveyor too (build x64 architecture is still pending, but x32 is passing)

**Comment by CarstVaartjes** [comment]
It's so weird! Discussing it with @esc on Google Groups, not sure what is going wrong and if it's really an issue... (bquery should have issues with this too)

**Comment by CarstVaartjes** [comment]
Hi,

a question: should i change the chunk ._getitem to expect a buffer as dest instead of a *char?

**Comment by FrancescElies** [comment]
Not sure, tests are passing, are you still having problems on your environment?
You could try and see what happens, or maybe try casting

**Comment by esc** [comment]
You could try and see if something has changed in numpy or cython by trying to compile with older versions, anaconda still has a bunch of older ones IIRC.

**Comment by FrancescElies** [comment]
If I see that correctly `iterchunksTest` inherits only from `MayBeDiskTest` I guess travis is not executing that test, it should also inherit from `TestCase`

**Comment by FrancescAlted** [comment]
That's correct.  Well spotted.

**Comment by CarstVaartjes** [comment]
*hides head in shame*

**Comment by FrancescAlted** [comment]
No no, that's not trivial and has bitten me a few times too.

2015-07-03 12:55 GMT+02:00 Carst Vaartjes <notifications@github.com>:

> *hides head in shame*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blosc/bcolz/pull/212#issuecomment-118315162>.
>



-- 
Francesc Alted

**Comment by CarstVaartjes** [comment]
Thanks! So it gives the same error as I would expect; I will test what it does when I change the expected type from *char to buffer in cython

**Comment by esc** [comment]
I'm not even sure buffer is available beyond 2.6

**Comment by CarstVaartjes** [comment]
Nope, it gives horrible errors :) Ndarray does too (because of dependencies etc) hmmm :/ I still don't understand that bquery and bdot seem to have no issues but inside bcolz we do (likely some cython thing).
So we cannot cdef a buffer while ndarray.data is a buffer? does anyone know if there is something available from numpy for this? I have been googling at it but cannot seem to find anything

**Comment by FrancescElies** [comment]
I am getting bit confused and having some questions, how does `iterchunks` differ from https://github.com/Blosc/bcolz/pull/153, is it performance? One should be able already to iterate over chunks, isn't it?
If the reason is performance wouldn't it be worth to apply those performance improvements on top of `__iter__` and `__next__` methods if possible?

If I understood correctly from a previous post https://github.com/Blosc/bcolz/pull/198#issuecomment-116316396 `iterchunks` shouldn't include leftovers right? Extensions writers still need to handle chunks and leftovers in two separate `for` loops.
On #153 we also had also a similar conversation, I understood that `iterblocks` could fill that requirement. 

Maybe would it be a better approach to use `PyBytes_AsString` instead of changing
the type declaration inside the function?

**Comment by FrancescAlted** [comment]
I think the last note by @FrancescElies really applies.  @CarstVaartjes would `iterblocks` be enough for your needs?

**Comment by CarstVaartjes** [comment]
Hi, the point (what I also made in the previous comments) was mostly that for me iterchunks explicitly should handle leftovers. The reason is that you do not want code to look like this:

    for array in iterchunks(carray_):
        do_stuff(a)

    if carray_.leftoverelements > 0:
        do_stuff(carray_.leftoverarray[:carray_.leftoverelements])

the second part is a bit ugly and really has no additional value. 
On the other hand, no clue how to solve the error we're getting here. it works perfectly fine in bquery where we cimport arrays... we added this there now:

    for array_len, array in iterchunks(carray_):
        do_stuff(a[:array_len])

and that works really well (and makes the code much more readable).
As i'm clueless in how to fix this with the cython weirdness popping up + a workaround of having it available in bquery, I propose to close this indeed. (just wanted to explain why you want more than just the chunks :)

**Comment by FrancescAlted** [comment]
Ok, so I think we can safely close this. At any rate,  `iterblocks` already deals with the leftovers, so again, that maybe enough for your needs.

**Comment by CarstVaartjes** [comment]
Thanks! I will check it out

**Pull request closed without merging**
