### PR TITLE
documentation upgrades

### PR DESCRIPTION
**Pull request by FrancescElies**
For the moment this PR is empty

TODO:
- Add `with statments` examples
- How to use bcolz as part of the infrastructure

### CODE REVIEW

**Comment by esc** [comment]
``embendsignature`` seems to work. Please cherry-pick the commit 38089e81534fbe9a464ce4eb97c91d4a6934582e from my fork which removes the remaining signatures from all the carray docstrings.

**Comment by esc** [comment]
Also, the following attributes of the carray aren't documented yet:

leftover_array 	
leftover_bytes 	
leftover_elements 	
leftover_ptr
nchunks
partitions

**Comment by esc** [comment]
The only weird thing about ``embedsignature`` is that it doesn't seem to remove the 'self' from the docstring, probably worth patching Cython for that.

**Comment by FrancescElies** [comment]
Thanks for 38089e8, now cherry-picked, I'll also add the description for those attributes in the following commits

**Comment by esc** [comment]
yay, more :beers:

**Comment by FrancescElies** [comment]
oh merged :) lovely.
Not sure how you guys feel about these changes, but if you feel like making any modifications to it or erasing any section, feel free to do so.

**Comment by FrancescElies** [comment]
:beers:

**Comment by FrancescAlted** [comment]
That's very nice.  I have spotted some small issues that will fix in master, but other than that, that's a great start for other developers wanting to use bcolz for their projects.

**Comment by FrancescAlted** [comment]
Fixed some things (name consistency, unfinished statements...) in bb6080e.

**Comment by FrancescElies** [comment]
Thanks for the corrections

**Pull request merged**
