### PR TITLE
Release gil for Blosc operation

### PR DESCRIPTION
**Pull request by FrancescAlted**

### CODE REVIEW

**Comment by FrancescAlted** [comment]
This has been tested with the `bench/multithreaded_copy.ipynb` notebook and dask can use multiple threads safely and without no locks at all.  Merging.

**Comment by CarstVaartjes** [comment]
nice! any benchmarks available?

**Comment by FrancescAlted** [comment]
Yup: http://nbviewer.jupyter.org/github/Blosc/bcolz/blob/master/bench/multithreaded_copy.ipynb

It is a simple one, but it is clear that the GIL is getting released for a multi-threaded application.

**Comment by CarstVaartjes** [comment]
Nice!!

**Pull request merged**
