### PR TITLE
Bitshuffle support

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR is intended for work on bitshuffle support.

### CODE REVIEW

**Comment by alimanfoo** [comment]
This PR is based on #285. I added one commit, which is to further upgrade c-blosc to the current master to get single byte bitshuffle support. After doing this, one test fails:

```
======================================================================
FAIL: test02 (test_carray.dtypesTest)
Testing carray constructor with a plain compound `dtype`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/aliman/SD1/src/github/alimanfoo/bcolz/bcolz/tests/test_carray.py", line 1855, in test02
    assert_array_equal(a, ac[:], "Arrays are not equal")
  File "/media/aliman/SD1/pyenv/bcolz_py34/lib/python3.4/site-packages/numpy/testing/utils.py", line 782, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/media/aliman/SD1/pyenv/bcolz_py34/lib/python3.4/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
Arrays are not equal
(mismatch 0.01999999999999602%)
 x: array([(1.0, 1.0), (1.0, 1.0), (1.0, 1.0), ..., (1.0, 1.0), (1.0, 1.0),
       (1.0, 1.0)], 
      dtype=[('f0', '<f4'), ('f1', '<f8')])
 y: array([(1.0, 1.0), (1.0, 1.0), (1.0, 1.0), ..., (1.0, 1.0), (1.0, 1.0),
       (1.0, 1.0)], 
      dtype=[('f0', '<f4'), ('f1', '<f8')])

----------------------------------------------------------------------
```

I added some logging to the test to look into how many array items mismatch and what the mismatching values are. Below `mismatch` is a boolean array from comparing `a != ac[:]`. Here is the output:

```
mismatch--> 6 (array([ 2730,  8191, 13652, 13653, 16383, 19114]),)
a[mismatch]--> [(1.0, 1.0) (1.0, 1.0) (1.0, 1.0) (1.0, 1.0) (1.0, 1.0) (1.0, 1.0)]
ac[mismatch]--> [(1.875, 1.000000236555934) (1.0, 5.263544247e-315)
 (1.0, 0.0004767922218888998) (0.7470588088035583, 1.0)
 (1.0, 0.0004767922794117647) (1.875, 1.0000002381857485)]
```

I'm thinking to wait for this issue to be resolved and a stable c-blosc 1.7.1 release is available before continuing work on bitshuffle support within bcolz.

**Comment by FrancescAlted** [comment]
I just pushed a [fix for bitshuffle](https://github.com/Blosc/c-blosc/commit/8c617dd786a68735c4d7051490585fcc4b3e50c7) that might solve the issue here.  Can you have it a try?

**Comment by alimanfoo** [comment]
Thanks Francesc, I'm on leave for 2 more weeks but will try it out as soon
as I'm back at work.

On Tuesday, 5 January 2016, FrancescAlted <notifications@github.com> wrote:

> I just pushed a fix for bitshuffle
> <https://github.com/Blosc/c-blosc/commit/8c617dd786a68735c4d7051490585fcc4b3e50c7>
> that might solve the issue here. Can you have it a try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Blosc/bcolz/pull/287#issuecomment-168970728>.
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Web: http://purl.org/net/aliman
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Tel: +44 (0)1865 287721

**Comment by FrancescAlted** [comment]
After 1.0.0 RC2 was released, bitshuffle is here, so closing.

**Pull request closed without merging**
