### PR TITLE
with statement

### PR DESCRIPTION
**Pull request by esc**
Context manager support for disk-based carrays

### CODE REVIEW

**Comment by esc** [comment]
Okay it seems to have worked, nice!

**Comment by esc** [comment]
It seems too easy...

**Comment by esc** [comment]
Anyone care to review this, also, if you are feeling up to it, could be extended to ctable.

**Comment by FrancescAlted** [comment]
That's cool.  Please extend it to ctables and add some docs for showing the behavior (or even better, rewrite most of the existing examples in docs to use the new context managers).

**Comment by FrancescElies** [comment]
I read this one and looks good to me, I also replicated the same behaviour for ctables

**Comment by FrancescElies** [comment]
Merging

**Comment by esc** [comment]
oh.. sweet!

**Pull request merged**
