### PR TITLE
Fe/asv

### PR DESCRIPTION
**Pull request by FrancescElies**
In case still interested, maybe first steps towards https://github.com/Blosc/bcolz/issues/116?

Modifications:
- Basic config file  `asv.conf.json`
- Added a small guide at `bench/README_asv.md`.
- Benchmarks would need some extra boilerplate (see  `bench/arange.py`, `bench/column_iter.py`) and _maybe some renaming asv does not like dashes (-)_.
- Modified benchmarks respect `run.sh` (they still could be ran with this script).
- Benchmarks for Python 3 not working, not sure why.

Running it:
- For the moment to get it running only adapted scripts should show up in the `bench` folder (run first `rm -f bench/*` and `git checkout bench/arange.py bench/column_iter.py bench/__init__.py`)
- Preview available at http://francescelies.github.io/bcolz/ (only some points can be seen, but if desired one could ran it for every commit in the repository, would take a while though).

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Hey Cesc, this is quite amazing.  I always envisioned doing this and now you did it! :)

Which steps would be required before merging this?  Do you want to instrument everything in bench/ or should we create a new, say, asv/ directory with just a few of instrumented ones?  As some of the existing benchmarks are a bit overlapping, I would use the second approach.

**Comment by FrancescElies** [comment]
Actually I also thought of making a new folder, but I was afraid of duplicating the benchmarks in two folders, if you are ok with that I would also prefer the second option :+1: 

For a basic beta version, before merging this we would need to pick some Benchmarks and adapt them, something similar to e.g. 9194e2b. 

For the moment asv only runs benchmarks for python 2.7 and latest packages marked as dependencies, later on could be extended to run those benchmarks for py26/py3 and different numpy versions in case that would be of interest.

I'll clean the git history and move some benchmarks to a new folder named `asv` as proposed. We should be able to easily add more benchmarks to it

**Comment by FrancescElies** [comment]
asv gets confused with folder with the same name, renamed to bench_asv

**Comment by FrancescElies** [comment]
Hi,

This contains now:
- `bench_asv` folder  containing three benchmark scripts and a small readme.
- Fix import mock error while running asv 530a39d
- Configuration file `asv.conf.json`
- some gitignore stuff

I would say this is at least ready for a review

**Comment by FrancescElies** [comment]
It also contains a badge 3355c1c, once you upload first results you are happy with, you might want to change the target `:target: http://your-url-here`

**Comment by FrancescAlted** [comment]
I think that, as a start, this is pretty good already.  We can complete the array of benchmarks a bit more in the future.  Thanks a lot for this one!

**Comment by FrancescElies** [comment]
No Problem.
By the way in case you try python 3.4 with asv highly likely you will get this error https://github.com/conda/conda/issues/1646

**Comment by FrancescAlted** [comment]
Just tried this, but I am having problems running it:

```
$ asv run
· Fetching recent changes.
· Creating environments
· Discovering benchmarks
·· Uninstalling from py2.7-cython-numexpr-numpy-pandas
·· Error running /usr/bin/git clone --shared /home/faltet/blosc/bcolz/bcolz /home/faltet/blosc/bcolz/env/68f7ca1eae1829581cfd22522d5a4d50/project                                                                                                                       
             STDOUT -------->
             
             STDERR -------->
             fatal: repository '/home/faltet/blosc/bcolz/bcolz' does not exist
Traceback (most recent call last):
  File "/home/faltet/miniconda/bin/asv", line 11, in <module>
    sys.exit(main())
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/main.py", line 36, in main
    result = args.func(args)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/commands/__init__.py", line 47, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/commands/run.py", line 122, in run_from_conf_args
    skip_existing_commits=args.skip_existing_commits
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/commands/run.py", line 197, in run
    benchmarks = Benchmarks(conf, regex=bench)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/benchmarks.py", line 285, in __init__
    for benchmark in benchmarks:
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/benchmarks.py", line 317, in disc_benchmarks
    env.install_project(conf)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/environment.py", line 345, in install_project
    build_root = self.build_project(commit_hash)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/environment.py", line 321, in build_project
    self.checkout_project(commit_hash)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/environment.py", line 318, in checkout_project
    self._repo.checkout(self._build_root, commit_hash)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/plugins/git.py", line 85, in checkout
    subrepo = Git(self._path, path, _checkout_copy=True)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/plugins/git.py", line 35, in __init__
    self._run_git(args, chdir=False)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/plugins/git.py", line 60, in _run_git
    [self._git] + args, **kwargs)
  File "/home/faltet/miniconda/lib/python2.7/site-packages/asv/util.py", line 431, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/usr/bin/git clone --shared /home/faltet/blosc/bcolz/bcolz /home/faltet/blosc/bcolz/env/68f7ca1eae1829581cfd22522d5a4d50/project' returned non-zero exit status 128
```

Hmm, I still need to get some speed on using asv, so not ready to announce it yet.

**Comment by FrancescElies** [comment]
having the same problem, not sure what's going on, I'll have a look

**Comment by FrancescElies** [comment]
`asv dev` just checks benchmarks once to see if everything is ok, this one works fine though.
```
❯ asv dev
· Discovering benchmarks
· Running 12 total benchmarks (1 commits * 1 environments * 12 benchmarks)
[  0.00%] ·· Building for /Users/cesc/anaconda/bin/python
[  0.00%] ·· Benchmarking /Users/cesc/anaconda/bin/python
[  8.33%] ··· Running arange.Suite.time_arange                                     65.16ms
[ 16.67%] ··· Running column_iter.Suite.time_sum_01                                38.01ms
[ 25.00%] ··· Running column_iter.Suite.time_sum_02                                37.85ms
[ 33.33%] ··· Running column_iter.Suite.time_sum_03                                63.44ms
[ 41.67%] ··· Running column_iter.Suite.time_sum_na_01                             46.27ms
[ 50.00%] ··· Running column_iter.Suite.time_sum_na_02                             45.28ms
[ 58.33%] ··· Running column_iter.Suite.time_tolist                               336.01ms
[ 66.67%] ··· Running column_iter.Suite.time_where_01                             366.88ms
[ 75.00%] ··· Running column_iter.Suite.time_where_02                             394.42ms
[ 83.33%] ··· Running column_iter.Suite.time_where_03                              32.33ms
[ 91.67%] ··· Running column_iter.Suite.time_where_04                              33.68ms
[100.00%] ··· Running concat.Suite.time_concatenate                               230.62ms
[100.00%] ····· problem size: (1000000) x 10 = 10^7
```

**Comment by FrancescAlted** [comment]
Right.  This works for me too.  Strange...

**Comment by FrancescElies** [comment]
I made a PR with a fix for that.
By the way I have no idea how many runs would do `asv run` I believe it would run all benchmarks for all commits, not sure about that.

You could use `asv run --skip-existing-commits -s 100 ALL` instead, `100` indicates you want to run the benchmark suite for 100 commits, if I understood it correctly it will pick up 100 commits from the master branch and run the bench on those

**Pull request merged**
