### PR TITLE
TestCase + fix for #179

### PR DESCRIPTION
**Pull request by FrancescElies**
I had some spare time, this PR should fix https://github.com/Blosc/bcolz/issues/179 ( test and bugfix  already proposed by @brentp in the previous link)

### CODE REVIEW

**Comment by cpcloud** [comment]
@esc any idea when this is going to be merged?

**Comment by cpcloud** [comment]
@FrancescElies can you add a test for slicing and also test that `repr(ctable_instance)` doesn't raise an error?

**Comment by cpcloud** [comment]
Oh i just saw that this was submitted 9 hours ago! @esc no rush

**Comment by cpcloud** [comment]
actually this doesn't fix the issue, i'll make another issue

**Comment by FrancescAlted** [comment]
LGTM.

**Comment by FrancescAlted** [comment]
Thanks @FrancescElies and @brentp !

**Pull request merged**
