### PR TITLE
Fe/cython coverage add c resources

### PR DESCRIPTION
**Pull request by FrancescElies**
Add c resources as proposed in https://github.com/Blosc/bcolz/pull/248#issuecomment-136352920

Might be helpful 
https://github.com/PyTables/PyTables/blob/develop/setup.py#L651

and then add the .c files in the MANIFEST.in like in:

https://github.com/PyTables/PyTables/blob/develop/MANIFEST.in#L5

### CODE REVIEW

**Comment by FrancescAlted** [comment]
I only see an empty commit here.  Is this intended?

**Comment by FrancescElies** [comment]
yes, without it somehow github closed automatically this PR, once I have new commits later on I will remove it

**Comment by FrancescElies** [comment]
Hi,

is this PR really necessary, or am I missing something?

Executing
```
setup.py build_ext --inplace 
python setup.py sdist
```

and then looking at the contents of the tar ball I see already cython and c sources in it:

```
bcolz-0.10.1.dev62
├── ANNOUNCE.rst
├── appveyor.yml
├── bcolz
│   ├── arrayprint.py
│   ├── attrs.py
│   ├── carray_ext.c
│   ├── carray_ext.pxd
│   ├── carray_ext.pyx
│   ├── check_blosc_version.h
│   ├── chunked_eval.py
│   ├── ctable.py
│   ├── defaults.py
│   ├── definitions.pxd
│   ├── __init__.py
│   ├── py2help.py
│   ├── PythonHelper.h
│   ├── tests
│   │   ├── all.py
│   │   ├── common.py
│   │   ├── __init__.py
│   │   ├── test_attrs.py
│   │   ├── test_carray_objects.py
│   │   ├── test_carray.py
│   │   ├── test_ctable.py
│   │   ├── test_ndcarray.py
│   │   └── test_queries.py
│   ├── toplevel.py
│   ├── utils.py
│   └── version.py
├── bcolz.egg-info
│   ├── dependency_links.txt
│   ├── pbr.json
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   └── top_level.txt
├── bench
│   ├── arange.py
│   ├── column-iter.py
│   ├── concat.py
│   ├── ctable-query.py
│   ├── eval-profile.py
│   ├── eval.py
│   ├── expression.py
│   ├── fill.py
│   ├── fromiter.py
│   ├── getitem.py
│   ├── iterator.py
│   ├── iter.py
│   ├── large_carray.py
│   ├── objpickles.py
│   ├── pandas-fromdataframe.py
│   ├── pandas-fromdataframe-strings.py
│   ├── pandas-todataframe.py
│   ├── pytables-fromhdf5.py
│   ├── pytables-tohdf5.py
│   ├── query.py
│   ├── run.sh
│   ├── serialization.py
│   ├── sum.py
│   └── zeros.py
├── c-blosc
│   ├── ANNOUNCE.rst
│   ├── bench
│   │   ├── bench.c
│   │   ├── CMakeLists.txt
│   │   ├── Makefile
│   │   ├── Makefile.mingw
│   │   └── plot-speeds.py
│   ├── blosc
│   │   ├── blosc.c
│   │   ├── blosc.h
│   │   ├── blosclz.c
│   │   ├── blosclz.h
│   │   ├── CMakeLists.txt
│   │   ├── config.h.in
│   │   ├── shuffle.c
│   │   ├── shuffle.h
│   │   └── win32
│   │       ├── pthread.c
│   │       ├── pthread.h
│   │       └── stdint-windows.h
│   ├── cmake
│   │   ├── FindLZ4.cmake
│   │   ├── FindSnappy.cmake
│   │   └── FindSSE.cmake
│   ├── CMakeLists.txt
│   ├── cmake_uninstall.cmake.in
│   ├── hdf5
│   │   ├── blosc_filter.c
│   │   ├── blosc_filter.h
│   │   ├── CMakeLists.txt
│   │   ├── example.c
│   │   └── README.rst
│   ├── internal-complibs
│   │   ├── lz4-r119
│   │   │   ├── lz4.c
│   │   │   ├── lz4.h
│   │   │   ├── lz4hc.c
│   │   │   └── lz4hc.h
│   │   ├── snappy-1.1.1
│   │   │   ├── add-version.patch
│   │   │   ├── msvc1.patch
│   │   │   ├── msvc2.patch
│   │   │   ├── snappy.cc
│   │   │   ├── snappy-c.cc
│   │   │   ├── snappy-c.h
│   │   │   ├── snappy.h
│   │   │   ├── snappy-internal.h
│   │   │   ├── snappy-sinksource.cc
│   │   │   ├── snappy-sinksource.h
│   │   │   ├── snappy-stubs-internal.cc
│   │   │   ├── snappy-stubs-internal.h
│   │   │   └── snappy-stubs-public.h
│   │   └── zlib-1.2.8
│   │       ├── adler32.c
│   │       ├── compress.c
│   │       ├── crc32.c
│   │       ├── crc32.h
│   │       ├── deflate.c
│   │       ├── deflate.h
│   │       ├── gzclose.c
│   │       ├── gzguts.h
│   │       ├── gzlib.c
│   │       ├── gzread.c
│   │       ├── gzwrite.c
│   │       ├── infback.c
│   │       ├── inffast.c
│   │       ├── inffast.h
│   │       ├── inffixed.h
│   │       ├── inflate.c
│   │       ├── inflate.h
│   │       ├── inftrees.c
│   │       ├── inftrees.h
│   │       ├── trees.c
│   │       ├── trees.h
│   │       ├── uncompr.c
│   │       ├── zconf.h
│   │       ├── zlib.h
│   │       ├── zutil.c
│   │       └── zutil.h
│   ├── LICENSES
│   │   ├── BLOSC.txt
│   │   ├── FASTLZ.txt
│   │   ├── H5PY.txt
│   │   ├── LZ4.txt
│   │   ├── SNAPPY.txt
│   │   ├── STDINT.txt
│   │   └── ZLIB.txt
│   ├── README_HEADER.rst
│   ├── README.rst
│   ├── README_THREADED.rst
│   ├── RELEASE_NOTES.rst
│   ├── RELEASING.rst
│   └── tests
│       ├── CMakeLists.txt
│       ├── Makefile
│       ├── print_versions.c
│       ├── test_all.sh
│       ├── test_api.c
│       ├── test_basics.c
│       └── test_common.h
├── conda.recipe
│   ├── bld.bat
│   ├── build.sh
│   └── meta.yaml
├── continuous-integration
│   └── appveyor
│       ├── install.ps1
│       └── run_with_env.cmd
├── coveralls_after_test_succes.sh
├── doc
│   ├── conf.py
│   ├── defaults.rst
│   ├── index.rst
│   ├── install.rst
│   ├── intro.rst
│   ├── make.bat
│   ├── Makefile
│   ├── my_package
│   │   ├── my_extension
│   │   │   ├── example_ext.pyx
│   │   │   └── __init__.py
│   │   ├── README.rst
│   │   ├── requirements.txt
│   │   └── setup.py
│   ├── opt-tips.rst
│   ├── reference.rst
│   └── tutorial.rst
├── LICENSES
│   ├── APPVEYOR-DEMO.txt
│   ├── BCOLZ.txt
│   ├── BLOSC.txt -> ../c-blosc/LICENSES/BLOSC.txt
│   ├── FASTLZ.txt -> ../c-blosc/LICENSES/FASTLZ.txt
│   ├── LZ4.txt -> ../c-blosc/LICENSES/LZ4.txt
│   ├── NUMPY.txt
│   ├── SNAPPY.txt -> ../c-blosc/LICENSES/SNAPPY.txt
│   ├── STDINT.txt -> ../c-blosc/LICENSES/STDINT.txt
│   └── ZLIB.txt -> ../c-blosc/LICENSES/ZLIB.txt
├── makefile
├── MANIFEST.in
├── pavement.py
├── persistence.rst
├── PKG-INFO
├── README.rst
├── RELEASE_NOTES.rst
├── requirements.txt
├── setup.cfg
├── setup.py
├── subtree-merge-blosc.sh
├── test_requirements.txt
└── THANKS.rst

23 directories, 189 files

```

**Comment by FrancescAlted** [comment]
True, the carray_ext.c is certainly in the generated tarball.  My guess is that newest setuptools do the generation automatically, and the MANIFEST.in just collect that .c files into the final tarball.

So, that's right, no further action is needed here.  Closing.

**Pull request closed without merging**
