### PR TITLE
TestCase sudden ndarray type

### PR DESCRIPTION
**Pull request by FrancescElies**
PR exposing issue https://github.com/Blosc/bcolz/issues/61

### CODE REVIEW

**Comment by FrancescElies** [comment]
Travis passed but still waiting for appveyor (I did several rebases a force push, travis aborted the execution of old commits but appveyor does not), I guess it's worth waiting.

**Comment by FrancescElies** [comment]
I had to slightly change the test to make it pass on windows using `_inttypes`, the rest of the tests are fine too.

**Comment by FrancescAlted** [comment]
This seems fine to me so :+1:  for merging.

**Comment by FrancescElies** [comment]
Sounds good to me :+1:

**Pull request merged**
