### PR TITLE
Fe/feature/leftovers and nleftovers

### PR DESCRIPTION
**Pull request by FrancescElies**
Integration https://github.com/Blosc/bcolz/pull/72 #132 and some leftovers' api tests
@esc I cherry picked you commits from #132 but I had to resolve some conflicts and the now appear as mine, not sure if there is a way better way of doing that.

If you like the tests you could cherry pick them in your PR our whatever you feel like

### CODE REVIEW

**Comment by esc** [comment]
@FrancescElies github still shows them as mine, perhaps a difference between author and commiter. If you cherry-pick my commits, I retain authorship but you become the commiter.

Anyway, looks rock solid to me, merging.

**Comment by esc** [comment]
May run into complex  issues when testing those across load and save of carrays, but good to have some base tests to work off.

**Comment by esc** [comment]
:beers:

**Comment by FrancescElies** [comment]
:beers:

**Pull request merged**
