### PR TITLE
Fe/cython coverage gcov

### PR DESCRIPTION
**Pull request by FrancescElies**
This is a different try-out using gcov approach rather than cython built in coverage analysis used in #246 #227

### CODE REVIEW

**Comment by FrancescElies** [comment]
at least c and h files seem to be listed by coveralls, but nosetests results disappeared from the results list and to see which lies are covered the c source needs to be on github https://coveralls.io/builds/3441555/source?filename=bcolz%2Fcarray_ext.c

**Comment by FrancescAlted** [comment]
Well, adding the .c sources is not necessarily a bad practice, rather the contrary.  Here it is a function that might be helpful for that purpose:

https://github.com/PyTables/PyTables/blob/develop/setup.py#L651

and then add the .c files in the MANIFEST.in like in:

https://github.com/PyTables/PyTables/blob/develop/MANIFEST.in#L5

Would you mind to file another PR with that?

**Comment by FrancescElies** [comment]
I just opened a new PR for that, but this one is not yet ready to merge though, the coverage of all python doesn't appear in coveralls anymore

**Comment by FrancescAlted** [comment]
That's right, '-fprofile-arcs -ftest-coverage -lgcov' will only have to be active during Travis runs, so it does not matter whether they have a performance impact or not.

**Comment by FrancescElies** [comment]
Still very patchy and /bcolz/carray_ext.c is getting more than a 100% coverage

**Comment by FrancescElies** [comment]
Now seems python and c files to be reported at the same time

**Comment by FrancescAlted** [comment]
This looks pretty good to me.  Should we wait until carray_ext.c is in the repo before merging this, right?

**Comment by FrancescElies** [comment]
Now we get 65% coverage on the carray_ext.c, once appveyor finishes I guess we could actually merge it, you'll see the percentage on coveralls but once you click on the file you won't be able to see which lines on `carray_ext.c` are covered because this files is not on github

**Comment by FrancescElies** [comment]
From what I see https://github.com/PyTables/PyTables/blob/develop/setup.py#L651 will get the c sources into the tar ball of the package right?

Coveralls needs the c source to be on github but keeping the pyx and the c file tracked by git is something we would like to avoid.

**Comment by FrancescAlted** [comment]
Yeah, let's start by merging this one then.  Thanks.

**Comment by FrancescAlted** [comment]
That's a good point: the procedure above is for putting the C sources in the tarball.  Now, that I think more about this, I don't really like the possibility to add the Cython C sources in the repo because if you change a single line in Cython, the diff in the C sources can be between 10 and 10 zillion lines, so not fun when you are reading diffs in a browser :(

Because of this, my vote would be -0 for adding the Cython C sources into the repo.  We should be happy to see total coverage then and not the line detail (which is pretty deceiving, but anyway).

**Comment by FrancescElies** [comment]
I agree, the best would be to get #246 working, and see pyx files coverage directly, but no luck yet

**Pull request merged**
