### PR TITLE
V1.5.4

### PR DESCRIPTION
**Pull request by esc**
Fresh new subtree-merge-blosc.sh and blosc

### CODE REVIEW

**Comment by esc** [comment]
Seems to have problems compiling LZ4...

**Comment by FrancescAlted** [comment]
Probably the merge command does not removed old 'internal-complibs/lz4-r119' directory (it should be 'internal-complibs/lz4-1.6.0'.

**Comment by esc** [comment]
Trying again.

**Comment by esc** [comment]
Ok, we are sticking with an older version for now.

**Pull request closed without merging**
