### PR TITLE
Vh/feature/with statement ctable

### PR DESCRIPTION
**Pull request by FrancescElies**
Replica PR  #135 for ctable (Context manager support for disk-based ctables)

TODO:
- changelog
- maybe change examples in docs https://github.com/Blosc/bcolz/pull/135#issuecomment-98608355

### CODE REVIEW

**Comment by esc** [comment]
I merge yours, you merge mind, and we'll write change the documentation in a separate PR?

**Comment by esc** [comment]
Just waiting on the windows CI.

**Comment by esc** [comment]
Windows CI sent me an email telling me that it failed.

**Comment by esc** [comment]
I am curious why did you call the branch ``vh/feature/*`` ?

**Comment by FrancescElies** [comment]
I copied your carray branch structure since it was almost the same I even copied the naming

**Comment by FrancescElies** [comment]
I see https://ci.appveyor.com/project/esc/bcolz/history the one that failed, not sure why, I rebased once maybe that's why, I forgot an invalid print statement for python 3

**Comment by esc** [comment]
oh, ok... that's very cool! perhaps use ``fe/*`` to indicate that the branch is in your namespace. ;)

**Comment by esc** [comment]
Alright let's wait for this one then, shall we.

**Comment by FrancescElies** [comment]
arg, I was wondering what vh was?¿?, hehe now I know (but since I had no idea copy paste seemed good enogh to me)

**Comment by esc** [comment]
It is fine, haven't seen anyone else except myself use it though, which is pretty cool.

**Comment by FrancescElies** [comment]
change documentation in a different PR :+1:

**Comment by esc** [comment]
Changelog in 94d197ea20811b66d7765312170c8f516dc57a75

**Pull request merged**
